# Generated by Django 5.2.5 on 2025-09-02 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_coinownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User that created/owns this coin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coins', to=settings.AUTH_USER_MODEL),
        ),
    ]
